### PR TITLE
Andrei/intake form page

### PR DESCRIPTION
**Pull request by andreisito**
# ✨ New in this PR ✨

## One liner: what did you do? 🚨 
Integrated question component and intake form overlay, can add to question list and reorder it by dragging.

## Coverage 🙆‍♀️
_use this section to break up your task into submodules and track progress_ 
 - [ x] Functioning add button.
 - [ x] Display and generate list of questions
 - [ x] Reorder list using drag-and-drop.  Establish persistence with question information.

## How can the reviewer test your code? 👩‍💻
Go into intake form page.  Click add circle to create generic questions.  Add information into questions.  Drag and reorder list, make sure they go into the right spots.

## Any bugs you encountered or still having trouble with? 🐛

EDIT: resolved 
Pending Bug:   onDragEnd is really inconsistent.  Draggable objects that are in the questions array are assigned indices on creation.  onDragEnd should be changing these indices as it gets reordered, but sometimes the program doesn't do that (not sure how to isolate this fully).  i.e a draggable created at index 0 is moved to index 3, but it is still referred to as index 0 in source.index which is used in onDragEnd.  Causes "jumps" when reordering list. 
Main issue with splice.  To replicate: 
1. in onDragEnd, add console.log(source.index) and console.log(destination.index)
2. Can also add 0, 1, 2 , ... in order to question components in-browser to track original placement of components
3. Console.log("some message") to the 2nd if statement in onDragEnd, reordering doesn't happen if index of source and destination match.
4. I'd mess around with first and last indices the most, most extreme errors. _

## Resources 📔
_link online resources and related PRs_ 

🧜‍♀️ cc: @shannonbonet @phoebeli23

### CODE REVIEW

**Comment by whuang7000** [comment]
I resolved the issue of reordering not working correctly, and made the ordering a lot smoother!

**Comment by whuang7000** [comment]
@AndreiLTan can you remove the draggable png and package-lock.json from the PR

**Review by bry-gavino — CHANGES_REQUESTED** [review]
Hey all! This looks absolutely amazing!!! Dragging the questions around feels so flawless--thank you so much for grinding through and figuring out how to preserve the internal data of the questions! Awesome job :) 

I have a few things that I'd appreciate to be addressed:
- I saw Will's comment about not being able to show the 6 dots on the frontend. Can I get a brief explanation as to why this is occurring, what issues arise from it, and ways/methods you've thought of fixing this?
- For the Question component itself, can we change the styling so that the component itself stretches/shrinks in width as the window is being stretched/shrunk? This can easily be done by replacing the static width value with a percentage value.
- Would it be possible to get the Layout bar on top to appear so that it aligns with the Figma design? (Basically making it consistent with the other pages you can navigate to instead of having that temporary back button)

Thank you both again for this amazing PR, Andrei and Will! Please let me know if you've got any questions :DD Seriously appreciate the work so much.

**Comment by andreisito** [comment]
@bry-gavino The six dots don't work because of the way we've had to implement the Draggable elements.  We to wrap the question components with Draggable to make the dnd feature work.  Initially I directly wrapped the question comp in its file, which let me inject dragHandleProps onto the six dots and made that the only draggable space on each question.  This doesn't work because the Droppable component expects Draggable components as children, not question components with Draggable properties.  So Will wrapped the question components in Draggable in getDraggable.  This works for dnd but we can't access the six dots element with dragHandleProps because it's within the question component.  To get the original design to work, I was considering wrapping a Draggable within question again, while maintaining getDraggable s.t. we limit the draggable space.

I'll go ahead and implement the other changes :)

**Comment by whuang7000** [comment]
> @bry-gavino The six dots don't work because of the way we've had to implement the Draggable elements. We to wrap the question components with Draggable to make the dnd feature work. Initially I directly wrapped the question comp in its file, which let me inject dragHandleProps onto the six dots and made that the only draggable space on each question. This doesn't work because the Droppable component expects Draggable components as children, not question components with Draggable properties. So Will wrapped the question components in Draggable in getDraggable. This works for dnd but we can't access the six dots element with dragHandleProps because it's within the question component. To get the original design to work, I was considering wrapping a Draggable within question again, while maintaining getDraggable s.t. we limit the draggable space.
> 
> I'll go ahead and implement the other changes :)

Hmm I actually think the draggable dots might be possible, let's sync at work session.

**Review by whuang7000 — APPROVED** [review]
can you remove package-lock.json?

**Review by j-keating0002 — CHANGES_REQUESTED** [review]
will address during worksession today but the functionality of the add button doesn't work on my end. double checking with bry to see if it's just me

**Comment by bry-gavino** [comment]
> will address during worksession today but the functionality of the add button doesn't work on my end. double checking with bry to see if it's just me

@j-keating0002 Just got it up and it's working for me! :'DDD Will have to take some time to review the code, but will try to merge this ASAP

**Comment by shannonbonet** [comment]
Completed in future PR

ORDER OF PRIORITY: 
- publish (simplify design, combine save/publish) **PRIORITY**
- delete **[PRIORITY]** 
- undo/redo

**Pull request merged**
