### PR TITLE
Andrei/buttons intake

### PR DESCRIPTION
**Pull request by andreisito**
# ✨ New in this PR ✨

## One liner: what did you do? 🚨 
Implementing buttons for intake form (add, delete, undo-redo).
## Coverage 🙆‍♀️
_use this section to break up your task into submodules and track progress_ 
 - [ x] Re-implement Add to useReducer
 - [ x] Implement delete button
 - [] Implement undo-redo

## How can the reviewer test your code? 👩‍💻
_Use add button on overlay and click trash icon next to every question.  Undo and redo are on overlay.  Check if text in questions are preserved during undo-redo_ 

## Any bugs you encountered or still having trouble with? 🐛
_Undo-redo still janky.  When redoing an undo, the restored question is reset.  Also going over getting history correct.  Need a better way to store history.  I think it has to do with using shallow copies to store questions._ 

## Resources 📔
_link online resources and related PRs_ 

🧜‍♀️ cc: @shannonbonet @phoebeli23

### CODE REVIEW

**Review by j-keating0002 — CHANGES_REQUESTED** [review]
@AndreiLTan hey andrei! it seems that the buttons aren't showing up at the bottom of each of the question cards. does your local branch show all of the icons?

image

**Comment by bry-gavino** [comment]
> @AndreiLTan hey andrei! it seems that the buttons aren't showing up at the bottom of each of the question cards. does your local branch show all of the icons?
> 
> image

@AndreiLTan To build on this, if the undo/redo is becoming too much of a hassle and you are blocked on it, feel free to commit or stash what you have of it so far, and then implement the delete button. Since undo/redo is a stretch feature, we want to prioritize the feature to delete. (It is okay to not have undo/redo, but we need delete) Ty Andrei!!

**Comment by andreisito** [comment]
Ok it should be updated now

**Review by shannonbonet — APPROVED** [review]
delete working for me now

**Comment by shannonbonet** [comment]
Damn amazing work Andrei - can't believe you wrote a whole reducer to get delete to work, and nice clean up of code! I ran linter on work + resolved merge conflicts from main. Should be good to merge. We start the backend grind tomo

**Review by j-keating0002 — COMMENTED** [review]
LFGG @AndreiLTan NICE WORK!! let's get these question components pulling from backend before the end of final hackathon. code looking amazing but make sure to remove any declarations that aren't being used :) WOOT WOOT

**Review by j-keating0002 — APPROVED** [review]

**Pull request merged**
